/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        LinterClass reader = new LinterClass();
        String path = "src/main/resources/gates.js";
        reader.semicolonChecker(path);
    }
}
